### PR TITLE
chore: update otel go dependencies

### PR DESCRIPTION
**Pull request by codeboten**
Address changes in the latest otel-go metrics API.

Signed-off-by: Alex Boten <aboten@lightstep.com>

### CODE REVIEW

**Review by jacobmarble — APPROVED** [review]

**Comment by jacobmarble** [comment]
@codeboten I'll pull down your branch and fix it up.

**Comment by jacobmarble** [comment]
@codeboten FYI this will take a few hours, but expect me to merge by tomorrow morning (US/Pacific).

**Comment by codeboten** [comment]
Thanks @jacobmarble, it looks like the dependencies used in the tests will need updating, but the dependencies themselves dependen on the otel2influx changes in this pr 😓

**Comment by jacobmarble** [comment]
Closed as #153

**Pull request closed without merging**
