### PR TITLE
fix(influx2otel): only map to histogram when all fields match

### LINKED ISSUE #312: influx2otel: error on field named "count"
Running the [influxdbreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/influxdbreceiver) in the opentelemetry collector,
we see metrics submission fail with  "failed to append to the batch".
Bisecting our metrics output, we find that it errors on lines like:

```
foo count=2i 
```

Renaming count to something else allows submission to work, but this is a third party application that we can't easily change.

### PR DESCRIPTION
**Pull request by seankhliao**
When AddPoint is called with the unknown metric type, it tries to infer the type from the given field names. Right now it infers histogram when any of the fields matches the histogram keys, but that leads to a lot of errors when your data isn't actually a histogram. Instead, only infer a histogram if all fields match the expected histogram keys.

Fixes #312
and maybe also https://github.com/influxdata/telegraf/issues/14371 ?

### CODE REVIEW

**Comment by seankhliao** [comment]
cc @jacobmarble I see you listed as the code owner on the otel collector side

**Review by jacobmarble — APPROVED** [review]
Thanks a bunch!

**Comment by ar1307** [comment]
Is there a chance that this change will be included in a future release, and possibly also in https://github.com/open-telemetry/opentelemetry-collector-contrib?
It is in main since over a year now.

**Comment by brtaylor-dev** [comment]
> Is there a chance that this change will be included in a future release, and possibly also in https://github.com/open-telemetry/opentelemetry-collector-contrib? It is in main since over a year now.

+1

What is the release process?

**Pull request merged**
