### PR TITLE
feat(otel2influx): Adds support for DELTA temporality metrics

### PR DESCRIPTION
**Pull request by garry-cairns**
Supporting https://github.com/influxdata/influxdb-observability/issues/6

### CODE REVIEW

**Comment by jacobmarble** [comment]
I do support the effort here, and I agree that we need to support delta metrics in this repository. However, the intent of the two "Prometheus" schemas is to provide a backward-compatible (as much as possible) schema for the [Telegraf Prometheus input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus).

Further, [OpenTelemetry provides some guidance on this topic](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/), and these Prometheus schemas should follow that guidance with at least best-effort priority.

I would suggest the `deltatocumulative` otel exporter, but it doesn't exist yet. A [related issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11434) and [related PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12140) have fizzled out.

Some options:
- gate backward-incompatible behavior behind a configuration field
- improve the [WIP `otel-v1` schema](https://github.com/influxdata/influxdb-observability/blob/v0.4.2/otel2influx/metrics_otel_v1.go) to meet your needs
- contribute a `deltatocumulative` exporter to otelcol-contrib

Thoughts?

**Comment by garry-cairns** [comment]
> I do support the effort here, and I agree that we need to support delta metrics in this repository. However, the intent of the two "Prometheus" schemas is to provide a backward-compatible (as much as possible) schema for the [Telegraf Prometheus input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus).
> 
> Further, [OpenTelemetry provides some guidance on this topic](https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/), and these Prometheus schemas should follow that guidance with at least best-effort priority.
> 
> I would suggest the `deltatocumulative` otel exporter, but it doesn't exist yet. A [related issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11434) and [related PR](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12140) have fizzled out.
> 
> Some options:
> 
>     * gate backward-incompatible behavior behind a configuration field
> 
>     * improve the [WIP `otel-v1` schema](https://github.com/influxdata/influxdb-observability/blob/v0.4.2/otel2influx/metrics_otel_v1.go) to meet your needs
> 
>     * contribute a `deltatocumulative` exporter to otelcol-contrib
> 
> 
> Thoughts?

Thoughts on what I view as the distinct points here in turn

* The comment on Prometheus formatting is interesting, and potentially suggests no fix is needed. Let me know your thoughts here. I presume influx uses these schemas when converting data from the [`spanmetrics` OTel collector processor[(https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanmetricsprocessor) because that processor itself uses/d a Prometheus format, but the `spanmetrics` processor has been deprecated in favour of the new [`spanmetrics` connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector), [in part to separate it from any Prometheus-specificity](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18678). I don't view the issue or the pull request as having any specific Prometheus component other than formatting. It's possible the new connector solves this problem if it doesn't end up using this format. I'll try to find some time to test that although you may know the answer already so let me know if so.
* The OTel guidance to which you link is both relevant and useful, but I would caveat with the point that it's still very much thinking in terms of converting a Prometheus-specific implementation, which I think is orthogonal to the real issue here.
* I don't see what a delta to cumulative processor would buy given the intent here is specifically to accept and persist delta metrics, those who want cumulative can already just output those, no?

In terms of your suggested options:

* configuring backward-incompatible behaviour seems sensible but without knowing more about the use-case of the old input plugin I can't opine. If `spanmetrics` output from an OTel collector will use this code on its way into telegraf via the influx OTel exporter regardless of whether telegraf is involved, even with the new connector, I'd prefer to see any configuration happening in the OTel exporter so users needn't worry about Telegraf.
* The new schema, without looking at it too deeply, would also seem a good place to address anything if the new connector doesn't simply solve this.
* As above, unless I'm misunderstanding your intent, I think a deltatocumulative processor almost does the opposite of what I want, which is for my OTel collector to be able to export

I'll try to find time to test with the new connector for `spanmetrics` and let you know the outcome. Thanks for your time looking at the PR.

**Comment by jacobmarble** [comment]
The proposed has been thoroughly analyzed in this PR. I'll review the code again; let's get it merged.

FYI, here's a branch where I am playing with span metrics. You might notice that the `spanmetrics` connector is configured for delta temporality, but the `servicegraph` connector is not -- it doesn't support delta temporality yet. I'd like to fix that, if I find spare cycles in the next couple weeks.

**Review by jacobmarble — COMMENTED** [review]
Please prefix the commit and PR title with `feat(otel2influx): `, then force push.

**Comment by garry-cairns** [comment]
> Please prefix the commit and PR title with `feat(otel2influx): `, then force push.

Done (assuming I've understood you correctly) now

**Pull request merged**
